### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by itsnotvalid** [ajdunlap/yesod-markdown#2]
While investigating with markdown usage in haskell, it's noted that pandoc is GPL'ed. Although Pandoc authors seems not be very aggressive in reinforcing that.

ref: http://code.google.com/p/pandoc/issues/detail?id=175

Yesod blog has a wish list which specifically states the dilemma: http://docs.yesodweb.com/blog/wishlist

**Comment by gregwebs** [comment]
By my understanding this library must be GPL. Please upload a new version with a GPL license (I think that is supposed to be a major version bump).

**Comment by gregwebs** [comment]
We could see if @pbrisbin interested in taking over maintenance of this package.

**Comment by ajdunlap** [comment]
Are you sure about that? My understanding is that I am allowed to release my code under a BSD license, just that the combined product of linking this software with Pandoc is GPL. (So if you distributed a linked binary it would be under the GPL.)

**Comment by gregwebs** [comment]
I am not a legal scholar, and I understand this issue is not straight-forward.
However, the FSF's stance on the issue seems fairly straight-forward:
http://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL

The BSD license and GPL are compatible. If I am reading the [FAQ](http://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean) correctly, then that means although BSD code can be used with GPL, the combination must be released as GPL.

So, technically it may be possible to BSD license this code because you are using cabal to distribute the GPL pandoc code, but this strategy seems potentially mis-leading at best.

**Comment by pbrisbin** [comment]
Hey guys, just wanted to say I have a version of this under the umbrella of my goodies repo. I dropped the macros but I do keep it compiling and have added back in sanitization by default. I've got no problems releasing that and taking over as maintainer. I haven't given much thought to licensing but I think since it uses pandoc internally it should be GPL.

**Comment by ajdunlap** [comment]
If you want to take it over that is fine with me.
